### ISSUE TITLE
可以考虑下把每个播客信息放到一个 YAML 文件中，然后自动生成 README

### ISSUE THREAD

**Issue by LinuxSuRen** [tech-podcasts/it-technology-podcast#6]
如题，如果有多人协作来修改同一个文件（README）的话，很容易出现冲突的情况。

下面是一个示例

https://github.com/opensource-f2f/episode/blob/master/.github/workflows/generator.yml

**Comment by LinuxSuRen** [comment]
我提供了一个 GitHub Action，可以简化这个过程

https://github.com/LinuxSuRen/yaml-readme

**Comment by stevending1st** [comment]
目前已修改工作流，感谢意见。
