### ISSUE TITLE
捐献本项目

### ISSUE THREAD

**Issue by stevending1st** [tech-podcasts/it-technology-podcast#8]
按照之前对 @LinuxSuRen 的承诺，本项目已超过预期 star，将捐献本项目至 https://github.com/tech-podcasts 或者 https://github.com/opensource-f2f。

感谢大家的支持。

**Comment by stevending1st** [comment]
感谢 @LinuxSuRen  @wey-gu @CaliCastle @showjason 各位对本仓库的支持，觉得还是有必要让各位知悉此动态，打扰了。

**Comment by stevending1st** [comment]
@LinuxSuRen 

新版预览链接：https://stevending1st.github.io/it-technology-podcast/

如果没有问题后面就这样弄过去了。

还有部分东西没弄好。

**Comment by LinuxSuRen** [comment]
这个太赞了！！！

**Comment by stevending1st** [comment]
目前已经完成对于原版的内容到网站的迁移。

也完成了两个版本的 Releases，主要是对各阶段的代码预留镜像，以便后续回溯。
- https://github.com/stevending1st/it-technology-podcast/releases/tag/v1.0.0 （最后一个原始版本的保存）
- https://github.com/stevending1st/it-technology-podcast/releases/tag/v2.0.0 （捐赠前的镜像保存）

对于原版内容也切出 [v1](https://github.com/stevending1st/it-technology-podcast/tree/v1.0.0) 分支对源码进行保存，方便预览。

捐赠后基于 2.0.0 的代码进行开发。

**Comment by stevending1st** [comment]
如果不出意外的话将于一周内对本项目进行迁移。

**Comment by wey-gu** [comment]
> @LinuxSuRen 
> 
> 
> 
> 新版预览链接：https://stevending1st.github.io/it-technology-podcast/
> 
> 
> 
> 如果没有问题后面就这样弄过去了。
> 
> 
> 
> 还有部分东西没弄好。
> 
> 

非常非常棒❤️

**Comment by stevending1st** [comment]
@LinuxSuRen 劳烦给个权限

> You don’t have the permission to create public repositories on tech-podcasts

**Comment by LinuxSuRen** [comment]
@stevending1st 权限已放开

**Comment by CaliCastle** [comment]
Docusaurus 赞一个

**Comment by stevending1st** [comment]
@LinuxSuRen
仓库已迁移，请给本仓库的权限。

**Comment by showjason** [comment]
酷！！！👍

**Comment by LinuxSuRen** [comment]
已经给 @stevending1st 添加 admin 权限
![image](https://user-images.githubusercontent.com/1450685/194741625-f17fb6fd-4b95-464a-b777-86c920da1ce2.png)

考虑到项目迁移已完成，我就先关闭该 issue 了

**Comment by stevending1st** [comment]
> 已经给 @stevending1st 添加 admin 权限

感谢。

> 考虑到项目迁移已完成，我就先关闭该 issue 了

还没有改好配置。
